### PR TITLE
Pull Request for Game Logic

### PR DESCRIPTION
**Pull request by MarcusAl**
Here I have implemented the game logic for the Tic Tac Toe project

### CODE REVIEW

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Hi Team :wave: 

You've done well so far :+1:  and I commend you for that :clap: 
However, there are still some changes to be made before this milestone can be approved.

## REQUIRED

* [x] Make sure your Pull Request has a meaningful title and a brief description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
* [x] No `puts/print` and `gets.chomp` outside `main.rb` file. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/only_main_print.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
* [x] Kindly display the status of the board after every move (valid or invalid)
* [x] Your game should be able to determine if the move is a winning move. From the screenshot below, your game couldn't detect a winning move, instead, it allowed the current player play multiple times.
image
image


### Make the requested changes and submit for another review.
## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Comment by MarcusAl** [comment]
Made requested changes, awaiting review

**Review by BrianSammit — CHANGES_REQUESTED** [review]
CHANGES REQUIRED :recycle: :red_circle: 
-------------
Hello team!! :wave: great job working on the required changes :clap: :hammer_and_wrench: 
However, there are a few changes to make to full fit this milestone :wrench: see them below :eyes: :point_down: 
------------------

- [ ] You have inside `bin` directory a file that is called `test.rb`. Kindly delete this file or add it to `.git ignore`. Remember that you shouldn't commit debugging code. [Here](https://questions.microverse.org/t/debugging-instructions-code/346) you can read de discussion about it. 
debugging_requirement

- [ ] When I make a draw move the game doesn't tell me about it and doesn't stop. Please fix that. 
Screenshot from 2021-02-22 09-46-59
------------
Please make the required changes above :hammer_and_wrench: :point_up_2: and send it agan for review. 
HAPPY CODING!!

**Comment by MarcusAl** [comment]
Made requested changes

**Review by rukundoeric — CHANGES_REQUESTED** [review]
# Status: ♻️ CHANGES REQUIRED ♻️
_Great job guys so far 👏 💯 👍. However, there are few issues we need to address before we move on, please check the comments below._

- ### To Highlight
  - [x] The project is clean. 💯
  - [x] The project follows Git flow. 💯
  - [x] It has a descriptive branch name 💯

- ### To Improve
  - [ ] [MANDATORY] When the game is won, it should determine and display the player who won the game. Ex: if player1 wins, it should display something like `player1 won!` not just `Game won!`.
  


_Please make all the required changes before you submit another code review. If you have any problems or concerns, you can reach out to me on @slack: Rukundo Eric 🚀 . I wish you all the very best 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/), 
@slack: Rukundo Eric**

**Review by smcommits — APPROVED** [review]
# Status: Approved :+1:

Hello!

**I can see that you have implemented the changes requested. Great Work!
This PR is now approved. You can go ahead and merge this branch. Congratulations and good luck with your next project!**

# 
Should you need any further support, please reach out to me on [slack](https://microverse-tse.slack.com/team/U01NB4QUR1S)

**Pull request merged**
