### PR TITLE
Add user prompts

### PR DESCRIPTION
**Pull request by Ghiftee**
This is a sketch of the TicTacToe game interaction between the players and the computer

### CODE REVIEW

**Review by rindrajosia — CHANGES_REQUESTED** [review]
**Changes required** :red_circle: 
Good introduction, However, there are bugs to fix:

REQUIRED:
- [x] game informs player if the selected move is invalid
- [x] game displays board after the player move
- [x] game informs player if the selected move is a winning move
- [x] game informs player if the selected move is a draw move
- [x] game repeats all actions for the next player's move

**Implementation details**
- [x] A loop is needed in this game ([OdinProject hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/loop.png))
- [x] Inside the loop, you should call actions repeated for each move
- [x] A loop needs to be terminated at some point (after a winning move or draw to be more specific)

Happy coding
Rindra Josia

**Review by acushlakoncept — CHANGES_REQUESTED** [review]
# Status: Changes Required ♻️

### Both of you have done an awesome job so far 👏 

✅ Game is asking players name
✅ Game tells which players' turn it is
✅ Game asks the player to select available moves
✅ Game displays board after the player move

Lets update this and we will be done with this milestone

- [x] [REQUIRED] game informs player if the selected move is invalid (without computing what an invalid move is). That is if player 1 selects position 5 and player two tries to select 5 again or number outside the bounds of 1-9, it should display invalid move - position taken
- [x] `[REQUIRED]` game informs the player if the selected move is a draw move (without computing draw)
- [x] @Ghiftee endeavor to always capitalize your commit messages, eg Fix linters error

### Make sure your linters are always passing before submitting for code review.

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

**Comment by MarcusAl** [comment]
Added requested changes

**Review by rukundoeric — CHANGES_REQUESTED** [review]
# Status: ♻️ CHANGES REQUIRED ♻️
_Great job guys so far 👏 💯 👍. However, there are some changes required, please check the comments bellow._

- ### To Highlight
  - [x] The project is clean. 💯
  - [x] Well done adding comments to improve code readability.💯
- ### To Improve
  - [x] [MANDATORY] Linters are failing. please fix them. 
  - [ ] [OPTIONAL] In your `README.md`, Include the steps to be followed to run this project locally.


_Please make all the required changes before you submit another code review. If you have any problem or concerns, you can reach out to me on @slack: Rukundo Eric 🚀 . I wish you all the very best 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/), 
@slack: Rukundo Eric**

**Review by enaburekhan — CHANGES_REQUESTED** [review]
# Status: Required changes:full_moon:
**Hi team!
Great job on working tirelessly to ensure this milestone gets approved as soon as possible. Your effort is highly commendable:clap::clap:. However, we just need to fix the linter issue and your project will be approved:muscle:.**

- [ ] Do not make any changes in config files - they represent style guidelines that you share with your team - which is a group of all Microverse students.

- If you think that change is necessary - open a Pull Request in this repository and let your code reviewer know about it. 
The project .rubocop.yml config is currently altered. Kindly see the screen-shot for reference: https://imgur.com/a/DX7EBrk. Copy a fresh config using this link: https://github.com/microverseinc/linters-config/blob/master/ruby/.rubocop.yml.

Make the above-required changes and when you are ready, request for another review.
Kindly drop your questions here and ping me on slack @ Eric Enaburekhan to respond.
Happy Coding:blush:
Eric Enaburekhan

**Review by arslanbisharat — APPROVED** [review]
# Approved 👏 

Thank you for making those changes requested by previous TSEs. Your project has met the minimum requirements. Good work! 

Best,
Arslan Bisharat

**Pull request merged**
